devDingco/13th_homework

.prettierrc
.vscode/settings.json
[240829]_section01/detail.css
[240829]_section01/detail.html
[240829]_section01/detail.js
[240829]_section01/myDiary(2).css
[240829]_section01/myDiary(2).html
[240829]_section01/myDiary(2).js
[240829]_section01/myDiary.js

과제 확인은 **myDiary(2), detail** 의 이름으로 되어있는 파일들로 확인부탁드립니다!
--> 일기 상세 페이지 이동 : `window.location.href`를 사용했습니다.
-> 버튼은 생성했으니 수정은 아직 작업중입니다. 최대한 빨리 수정해서 업데이트 하겠습니다!

[240830] section02 필수과제 제출

---

homework/day01.js
homework/day04_일기.css
homework/day04_일기.html
homework/day04_일기.js

day04과제 대략완성
css 흐림효과 완성, 드롭다운 미완성
js 하는중

day05과제_미완성  정아영

---

.vscode/settings.json
CSS&JS 마스터/수정.css
CSS&JS 마스터/수정.html
CSS&JS 마스터/수정.js
CSS&JS 마스터/일기보관함.css
CSS&JS 마스터/일기보관함.html
CSS&JS 마스터/일기보관함.js
CSS&JS 마스터/일기상세페이지.css
CSS&JS 마스터/일기상세페이지.html
CSS&JS 마스터/일기상세페이지.js

[240902] Day05 과제제출(문희철)

---

homework/detail.css
homework/detail.html
homework/detail.js
homework/index.css
homework/index.html
homework/index.js

git 오류는 수요일에 QT로 정리해보겠습니다...
아직 트러블 슈팅 중입니다..ㅠ

[240903] 박진태 Day07 과제

---

01-diary/common.js
01-diary/detail/detail.css
01-diary/detail/detail.html
01-diary/detail/detail.js
01-diary/detail/detail_1208.css
01-diary/detail/detail_update.css
01-diary/detail/detail_update.html
01-diary/detail/detail_update.js
01-diary/detail/detail_update_mobile.css
01-diary/index.css
01-diary/index.html
01-diary/index.js
01-diary/index_1208.css
01-diary/index_mobile.css

[240903] CSS&JS 마스터 Section 04 과제 제출 - 최홍식

---

.vscode/settings.json
diary.html
diaryDetail.html
modules/diary.js
modules/diaryDetail.js
styles/diary.css
styles/diaryDetail.css
styles/diary_mobile.css
styles/reset.css

[0905] 윤준수 section05 과제 

---

depth01/myDiary_detail.css
depth01/myDiary_detail.html
depth01/myDiary_detail.js
myDiary.css
myDiary.html
myDiary.js

[240905].day09 section05
[240906].day10 section06
CSS: 모달, 토스트, 이미지핏, 스켈레톤
JS: 클릭으로 모달종료, ESC로 모달종료, 일기내용 복사, 삭제모달, 모달시 스크롤방지, API로 이미지로드
특이사항 없음
`[해결완료]: 일기 메인페이지에서 삭제기능, 이벤트 버블링 방지 및 올바른 배열 매칭하여 찾는 방법`
`>> 이벤트 리스너 생성할 때 리스너에 파라미터로 인덱스넘버 전달하여 카드(일기)마다 다른 이벤트가 발생하도록 설계`
`[해결완료]: 이중모달 기능실현: 이중모달 레이아웃 완성하였으나 버튼 클릭 시 인풋값 유효성 검사 필요, 기존 일기 작성 기능 망가지는 이슈`
`>> 그냥 함수를 잘못 짰음. 멍청이슈. 리팩토링하여 정상작동 확인. 기존기능 + 신규 모달기능으로 일기등록 2트랙으로 가능.`
toDo...
기본 반응형 break 375px; 대응 완료, 추가로 메인화면 4단 grid 레이아웃 break 1024px;로 대응 예정
화면이 밋밋하여 그라디언트 오버레이 등 스타일 적극적으로 활용할 수 있는 방안 탐색 중.. 과제데이 때 대응 예정
!! 이슈: 일기 필터기능: 필터기능 활성 시 하드코딩된 배열 참조하여 올바르게 매칭되지 않는 이슈

[240906].day10__section06 이하성 과제제출

---

css/index.css
index.html
js/index.js

todo: intersectionobserver api. indexeddb, loading image

240909 정치영 implement image loader

---

다이어리/diary-detail.html
다이어리/diary-detail.js
다이어리/diary-edit.js
다이어리/diary.css
다이어리/diary.html
다이어리/diary.js
다이어리/utils/onKeyPress.js

[240909] section06 강예슬 과제제출

---

나만의 일기장/detail.css
나만의 일기장/detail.html
나만의 일기장/detail.js
나만의 일기장/myDiary.css
나만의 일기장/myDiary.html
나만의 일기장/myDiary.js
나만의 일기장/photo.css
나만의 일기장/photo.html
나만의 일기장/photo.js

+ detail page에서 삭제 되었을 때 toast 추가
(myDiary.html 파일 : 일기보관함(메인)
detail.html 파일 : 일기 상세보기 페이지
photo.html 파일 : 사진보관함 )

[240906] 김민정 section06 필수과제 제출

---

diary.html
modules/diary.js
styles/diary.css
styles/global.css

[240909] 윤준수 section07 제출

---

depth01/myDiary_detail.js
myDiary.css
myDiary.html
myDiary.js

filter 디자인, 기능구현
search 디자인, 기능구현
mobile 반응형 375대응
필터 오류 해결 및 검색기능 추가
`[해결완료]: 일기 메인페이지에서 삭제기능, 이벤트 버블링 방지 및 올바른 배열 매칭하여 찾는 방법`
` >> 이벤트 리스너 생성할 때 리스너에 파라미터로 인덱스넘버 전달하여 카드(일기)마다 다른 이벤트가 발생하도록 설계`
`[해결완료]: 이중모달 기능실현: 이중모달 레이아웃 완성하였으나 버튼 클릭 시 인풋값 유효성 검사 필요, 기존 일기 작성 기능 망가지는 이슈`
` >> 그냥 함수를 잘못 짰음. 멍청이슈. 리팩토링하여 정상작동 확인. 기존기능 + 신규 모달기능으로 일기등록 2트랙으로 가능.`
`[해결완료]: 일기 필터기능: 필터기능 활성 시 하드코딩된 배열 참조하여 올바르게 매칭되지 않는 이슈`
` >> 필터, 검색 시 배열 쪼개서 세션스토리지에 임시 저장 후 map으로 데이터 뿌려줌, 데이터 다 뿌려주면 세션스토리지 초기화하도록 기능`
toDo...
모달 다크모달
무한스크롤
메인 일기장 4단 그리드
1024~768 middle size 반응형추가 대응
페이지 데코

[240909].day11__section07 이하성 과제제출

---

diary.html
modules/addDiaryModule.js
modules/diary.js
modules/documentElement.js
modules/util.js
styles/diary.css

[240910] 윤준수 section08 과제

---

depth01/myDiary_detail.js
legacy.html
myDiary.css
myDiary.html
myDiary.js

Section 07 기본 요구사항
Section 08 기본 요구사항
style: 전역 다크모드 적용(메인), 모바일 미대응
마우스 위치에 따른 배경 오버레이 효과 적용
script: 살짝 정돈
toDo...
메인 일기장 4단 그리드
무한스크롤
페이지네이션
768~1024 middle size 반응형추가 대응

[240910].day12__section08 이하성 과제제출

---

homework/section07/css/index.css
homework/section07/index.html
homework/section07/javascript/index.js

Day12 과제물은 section07에서 작성하였으며, 샘플코드 바탕 위에서  JS 과제만 완성했습니다..

[240911] 박진태 Day12 과제

---

css/index.css
edit.html
index.html
js/edit.js
js/functool.js
js/index.js

- debounce throttle을 모듈러하게 설계했습니다
- 무한스크롤 테스트완료
- todo: 텍스트검색, 페이지네이션

[240912] 정치영

---

daily.html
style/dailyStyle.css

pretendard 적용하고 font cross-browsing 확인하고 sementic tag로 html 구성하는 게 과제 맞나요?

[240912] CSS&JS 마스터 Section 09 과제제출 - 류지승

---

나만의 일기장/myDiary.html

[240912] section09 김민정 필수과제 제출

---

다이어리/diary-detail.css
다이어리/diary-detail.html
다이어리/diary-detail.js
다이어리/diary-edit.css
다이어리/diary-edit.html
다이어리/diary.css
다이어리/diary.html
다이어리/diary.js
다이어리/utils/onCloseSingleModal.js
다이어리/utils/onFocusActiveModal.js
다이어리/utils/onTriggerModal.js
다이어리/utils/upScroll.js

[240913] section09 강예슬 과제제출

---

trip-talk/src/App.css
trip-talk/src/App.tsx
trip-talk/src/components/button/Button.tsx
trip-talk/src/components/createPost/CreatePost.tsx
trip-talk/src/components/createPost/createPost.module.css
trip-talk/src/components/imageUploader/ImageUploader.tsx
trip-talk/src/components/input/Input.tsx
trip-talk/src/index.css
trip-talk/src/main.tsx

[240923] 강예슬 Day17 과제 제출

---

trip-talk/package-lock.json
trip-talk/package.json
trip-talk/src/app/layout.tsx
trip-talk/src/app/routes/boards/new/page.tsx
trip-talk/src/commons/settings/apollo-setting.tsx

[240930] 강예슬 DAY22 과제 완료

---

메인캠프/maincamp/my-board/package.json
메인캠프/maincamp/my-board/src/app/boards/new/page.tsx
메인캠프/maincamp/my-board/src/app/layout.tsx
메인캠프/maincamp/my-board/src/commons/setting/apollo-setting.tsx
메인캠프/maincamp/my-board/yarn.lock

[240927] 김민정 Day22 과제 제출

---

03-trip/03-03-Next/next.config.mjs
03-trip/03-03-Next/src/app/boards/[boardId]/page.tsx
03-trip/03-03-Next/src/app/boards/[boardId]/styles.module.css
03-trip/03-03-Next/src/app/boards/detail/styles.module.css
03-trip/03-03-Next/src/app/boards/new/page.tsx
03-trip/03-03-Next/src/app/boards/page.tsx
03-trip/03-03-Next/src/app/boards/styles.module.css
03-trip/03-03-Next/src/app/globals.css

1. 공통
2. 게시글등록
3. 게시글조회
등록페이지 boards/new:: module css 작업 필요 // component 분해 필요
구?조 할당 분해 이해 못하는 중 차근히 공부하며 리팩토링 및 디벨롭 하겠습니다

[241001] 이하성 Day24 과제 제출

---

my-app/src/app/boards/[boardId]/edit/page.tsx
my-app/src/app/boards/[boardId]/edit/styles.module.css
my-app/src/app/boards/[boardId]/page.tsx
my-app/src/app/boards/page.tsx
my-app/src/app/globals.css
my-app/src/components/boards-write/index.tsx

컴포넌트나 데이터 주고받는 과정에서 시간을 많이 소모해서 미완성입니다.

[241004] 이찬우  DAY25 과제 제출

---

maincamp/my-app/src/app/boards/[boardId]/page.tsx
maincamp/my-app/src/app/boards/css/styles.module.css
maincamp/my-app/src/app/boards/page.tsx

Day24 목록 클릭 시 undefined 오류 수정 중 입니다.

[241010] 메인캠프 과제제출 서준형

---

my-app/package.json
my-app/src/app/globals.css
my-app/src/components/boards-detail/detail/index.tsx
my-app/src/components/boards-detail/detail/queries.ts
my-app/src/components/boards-write/hook.ts
my-app/src/components/boards-write/index.tsx
my-app/src/components/boards-write/queries.ts
my-app/yarn.lock

[241011] 이찬우  DAY29 과제 제출

---

메인캠프/maincamp/my-board/src/commons/graphql/gql.ts
메인캠프/maincamp/my-board/src/commons/graphql/graphql.ts
메인캠프/maincamp/my-board/src/components/boards-detail/comment-write/hooks.ts
메인캠프/maincamp/my-board/src/components/boards-list/list/hooks.ts
메인캠프/maincamp/my-board/src/components/boards-list/list/index.tsx
메인캠프/maincamp/my-board/src/components/boards-list/list/queries.ts
메인캠프/maincamp/my-board/src/components/boards-list/pagination/hook.ts
메인캠프/maincamp/my-board/src/components/boards-list/pagination/index.tsx
메인캠프/maincamp/my-board/src/components/boards-list/pagination/types.ts
메인캠프/maincamp/my-board/src/components/boards-write/hooks.ts
메인캠프/maincamp/my-board/src/components/boards-write/queries.ts

Day29, 30 필수과제는 수정해서 곧 제출하겠습니다.

[241014] 김민정 Day31 필수과제 제출

---

my-app/src/app/boards/page.tsx
my-app/src/app/boards/queries.ts
my-app/src/commons/layout/banner/styles.module.css
my-app/src/components/boards-list/list/index.tsx
my-app/src/components/boards-list/list/styles.module.css
my-app/src/components/boards-list/list/types.ts
my-app/src/components/boards-list/pagination/hook.ts
my-app/src/components/boards-list/pagination/index.tsx
my-app/src/components/boards-list/pagination/styles.module.css
my-app/src/components/boards-list/pagination/type.ts

[241015] 이찬우  DAY31 과제 제출

---

Next/nextproject/next-app/package.json
Next/nextproject/next-app/src/app/component/board-detail/comment-list-item/hook.ts
Next/nextproject/next-app/src/app/component/board-detail/comment-list-item/index.tsx
Next/nextproject/next-app/src/app/component/board-detail/comment-list-item/style.module.css
Next/nextproject/next-app/src/app/component/board-detail/comment-list-item/types.ts
Next/nextproject/next-app/src/app/component/board-detail/comment-list/hook.ts
Next/nextproject/next-app/src/app/component/board-detail/comment-list/index.tsx
Next/nextproject/next-app/src/app/component/board-detail/comment-write/hook.ts
Next/nextproject/next-app/src/app/component/board-detail/comment-write/index.tsx
Next/nextproject/next-app/src/app/component/board-detail/detail/hook.ts
Next/nextproject/next-app/src/app/component/board-list/pagination/style.module.css
Next/nextproject/next-app/src/commons/graphql/gql.ts
Next/nextproject/next-app/src/commons/graphql/graphql.ts
Next/nextproject/next-app/yarn.lock

댓글 수정 미완성, 
무한스크롤 후 댓글 등록 시 스크롤 초기화 됨

[241016] 과제 안상현

---

trip-talk/src/app/_components/OpenApi/OpenApi.tsx
trip-talk/src/app/openapis/page.tsx

1. 게시글작성
2. 나만의컨텐츠목록[오픈API]
=> 오픈API 종류에는 제한을 두지 않습니다.(ex, 강아지목록, 고양이목록 등)
=> 디자인 및 무한스크롤, 페이지내이션 등 어떠한 기능에도 제한을 두지 않으므로 자유롭게 만들어 주세요.
=> 페이지에서 직접 코드를 작성하기 보단, src/components/openapis-list/index.ts 의 경로에 컴포넌트를 만들고 조립해 주세요.
3. 컴포넌트[리팩토링]
=> 타입에러가 감지되어 빨간 밑줄이 그어지는 부분에 타입스크립트를 적용하여 문제를 해결해 주세요.
=> 유지보수가 쉽도록 파일을 hook.ts, index.tsx, queries.ts, styles.module.css , types.ts 로 분리해 주세요.

[241017] 강예슬 과제 제출

---

trip-talk/next.config.mjs
trip-talk/src/app/_api/openapis/getTourOpenapi.ts
trip-talk/src/app/_component/modal/ModalTemplete.tsx
trip-talk/src/app/_component/openapiPage/OpenapiItem.tsx
trip-talk/src/app/_hooks/boardDetail/useCommentInput.ts
trip-talk/src/app/_types/commentTypes.d.ts
trip-talk/src/app/openapis-list/page.tsx

1. 공통
2. 게시글작성
3. 나만의컨텐츠목록[오픈API]
=> 오픈API 종류에는 제한을 두지 않습니다.(ex, 강아지목록, 고양이목록 등)
=> 디자인 및 무한스크롤, 페이지내이션 등 어떠한 기능에도 제한을 두지 않으므로 자유롭게 만들어 주세요.
=> 페이지에서 직접 코드를 작성하기 보단, src/components/openapis-list/index.ts 의 경로에 컴포넌트를 만들고 조립해 주세요.
4. 컴포넌트[리팩토링]
=> 타입에러가 감지되어 빨간 밑줄이 그어지는 부분에 타입스크립트를 적용하여 문제를 해결해 주세요.
=> 유지보수가 쉽도록 파일을 hook.ts, index.tsx, queries.ts, styles.module.css , types.ts 로 분리해 주세요.

[241017] 윤준수 DAY 33 과제 완료

---

frontend/next-homework/package.json
frontend/next-homework/src/app/components/boards-detail/comment-list/hook.ts
frontend/next-homework/src/app/components/boards-detail/comment-list/queries.ts
frontend/next-homework/src/app/components/boards-detail/comment-write/hook.ts
frontend/next-homework/src/app/components/boards-detail/comment-write/index.tsx
frontend/next-homework/src/app/components/boards-detail/detail/hook.ts
frontend/next-homework/src/app/components/boards-detail/detail/index.tsx
frontend/next-homework/src/app/components/boards-detail/detail/styles.module.css
frontend/next-homework/src/app/components/boards-list/list/index.tsx
frontend/next-homework/src/app/components/boards-list/pagination/hook.ts
frontend/next-homework/src/app/components/boards-list/pagination/index.tsx
frontend/next-homework/src/app/components/boards-write/hook.ts
frontend/next-homework/src/app/components/boards-write/index.tsx
frontend/next-homework/src/app/components/boards-write/queries.ts
frontend/next-homework/src/app/layout.tsx
frontend/next-homework/src/commons/graphql/gql.ts
frontend/next-homework/src/commons/graphql/graphql.ts
frontend/next-homework/src/commons/layout/index.tsx
frontend/next-homework/yarn.lock

(*과제는 따로 폴더를 분리해서 올려서 이 pr에는 커밋 내역이 없습니다!)
[커밋 히스토리](https://github.com/kimsudang/sesac-codecamp/commits/main/)
등록 페이지 구현 완료, 상세 페이지 (기능만) 구현 완료, 댓글 작업 중입니다.
오늘 중으로 댓글부분(등록, 수정, 삭제, 기타 디자인 등) 보완 및 구현 예정입니다.
**질문**
커밋을 할 때 어느정도 단위로 해야할 지 잘 모르겠습니다. 
지금까지는 inatall 한 내용에 대해서도 따로 커밋을 작성했는데, install+기능 구현 완료까지 하고 커밋을 해야하는지 아니면 css design이 변경되었을 때처럼 작은 단위로 커밋해도 될까요?
> ![스크린샷 2024-10-18 오전 9 30 59](https://github.com/user-attachments/assets/05b160eb-4d4a-4eae-b77c-52b0ae73a656) 
> ![스크린샷 2024-10-18 오전 9 31 37](https://github.com/user-attachments/assets/e821f006-930e-4856-b3fe-d306b5d58f30)

[241018]김수연 과제 제출

---

class-practice/my-app/package.json
class-practice/my-app/src/app/layout.tsx
class-practice/my-app/src/app/section18/18-01-image-upload/page.tsx
class-practice/my-app/src/app/section18/18-02-image-ref/page.tsx
class-practice/my-app/src/app/section18/18-03-image-validation/page.tsx
class-practice/my-app/src/app/section18/18-04-image-with-board/page.tsx
class-practice/my-app/src/app/section18/18-05-image-with-board-typescript/page.tsx
class-practice/my-app/src/commons/libraries/18-03-validation-file.ts
class-practice/my-app/src/commons/settings/18-01-apollo-upload-setting.tsx
class-practice/my-app/yarn.lock
homework/my-app/next.config.mjs
homework/my-app/package.json
homework/my-app/src/app/layout.tsx
homework/my-app/src/commons/settings/apollo-setting.tsx
homework/my-app/src/components/boards-write/hook.ts
homework/my-app/src/components/boards-write/index.tsx
homework/my-app/src/components/boards-write/queries.ts
homework/my-app/src/components/boards-write/style.module.css
homework/my-app/yarn.lock

미완성
1. 업로드한 이미지 게시글에 로드
2. 5MB이상 파일 제한
3. 컴포넌트 리팩토링

[241022]DAY36필수과제제출_임윤정

---

frontend/next-homework/src/app/_components/boards-detail/comment-list/hook.ts
frontend/next-homework/src/app/_components/boards-detail/comment-list/index.tsx
frontend/next-homework/src/app/_components/boards-detail/comment-list/queries.ts
frontend/next-homework/src/app/_components/boards-write/hook.ts
frontend/next-homework/src/app/_components/boards-write/index.tsx
frontend/next-homework/src/app/_components/boards-write/types.ts
frontend/next-homework/src/commons/layout/footer/index.tsx
frontend/next-homework/src/commons/layout/footer/styles.module.css
frontend/next-homework/src/commons/layout/index.tsx
frontend/next-homework/src/commons/layout/navigation/hook.ts
frontend/next-homework/src/commons/layout/navigation/index.tsx
frontend/next-homework/src/commons/layout/navigation/styles.module.css

무한 스크롤 기능 수정
게시글 수정 시 기본 값 받아오기 및 댓글 수정 기능 구현 중

[241023] 김수연 과제 제출

---

class-practice/my-app/src/app/section20/20-01-callback-promise-asyncawait/.prettierrc
class-practice/my-app/src/app/section20/20-01-callback-promise-asyncawait/index.html
class-practice/my-app/src/app/section20/20-02-map-el/page.tsx
class-practice/my-app/src/app/section20/20-03-prev-state/page.tsx
class-practice/my-app/src/app/section20/20-04-graghql/mutation.txt
class-practice/my-app/src/app/section20/20-04-graghql/query.txt
homework/my-app/src/app/boards/mypage/page.tsx
homework/my-app/src/app/boards/mypage/style.module.css
homework/my-app/src/app/globals.css
homework/my-app/src/components/boards-list/banner/index.tsx
homework/my-app/src/components/boards-list/banner/style.module.css
homework/my-app/src/components/boards-list/list/hooks.ts
homework/my-app/src/components/boards-list/list/index.tsx
homework/my-app/src/components/boards-list/list/style.module.css
homework/my-app/src/components/boards-list/search/style.module.css
homework/my-app/src/components/style.module.css

[241023]DAY38과제제출_임윤정

---

server/configs/mongoDB.config.ts
server/configs/postgreSQL.config.ts
server/src/app.module.ts

어제 일정이 있어서 과제를 하지 못했습니다. 
이번주 elastic search & redis setting 및 역인덱스 구현까지 해보려고 합니다. 
db 연결하고 백엔드 로직짠다음 search deboucing(이번주 주말까지) 시간 남으면 jwt 공부
->  다음주 plan server JWT를 사용한 인증을 위해 Guard 구현, access token 및 refresh token 처리 로직 
client  NextAuth.js를 통해 access token과 refresh token 기반 인증 시스템을 구현(expiration time)
퍼블리싱은 천천히 해도 괜찮을까요 ?

[241024] 류지승

---

Next/nextproject/next-app/package.json
Next/nextproject/next-app/src/app/boards/page.tsx
Next/nextproject/next-app/src/app/component/board-detail/comment-write/comment-write-box/hook.ts
Next/nextproject/next-app/src/app/component/board-detail/detail/index.tsx
Next/nextproject/next-app/src/app/component/board-list/list/hook.ts
Next/nextproject/next-app/src/app/component/board-list/list/index.tsx
Next/nextproject/next-app/src/app/component/board-list/list/types.ts
Next/nextproject/next-app/src/app/component/board-list/pagination/style.module.css
Next/nextproject/next-app/src/app/component/board-write/hook.ts
Next/nextproject/next-app/src/app/component/board-write/index.tsx
Next/nextproject/next-app/src/app/component/commons/layout/background/index.tsx
Next/nextproject/next-app/src/app/component/commons/layout/background/styles.module.css
Next/nextproject/next-app/src/app/component/commons/layout/index.tsx
Next/nextproject/next-app/src/app/component/commons/layout/styles.module.css
Next/nextproject/next-app/src/app/globals.css
Next/nextproject/next-app/src/app/layout.tsx
Next/nextproject/next-app/yarn.lock

OpenWeather API를 이용하여 프로젝트 진행 중
자신의 위치를 잡아 그 곳의 날씨를 기반으로 배경을 바꿔주는 작업을 진행 중(배경 사진은 현재 과제파일 내에 있는 것으로 대체)
아직 전체적인 기획은 없지만 API는 유지한채로 진행 할 예정

[241024] React OpenWeather API 안상현

---

03-trip/03-03-Next/.eslintrc.json
03-trip/03-03-Next/src/app/boards/[boardId]/edit/page.tsx
03-trip/03-03-Next/src/app/boards/new/page.tsx
03-trip/03-03-Next/src/commons/hocs/withLoginCheck.tsx
03-trip/03-03-Next/src/commons/hooks/useLoginUser.ts
03-trip/03-03-Next/src/commons/layout/index.tsx
03-trip/03-03-Next/src/commons/settings/apollo-setting.tsx

day 42. => 로그인 유지, 스토리지 활용한 토큰 저장, 로그인 여부에 따른 화면 분기 [ 완성 ]
day 33. => OpenApi 활용 미흡
day 35. => 백엔드 기초 및 파이어베이스 미흡
day 38. => 마이페이지 퍼블리싱 미흡
day 39. => Zustand, fetchPolicy, 상품페이지 퍼블리싱 미흡
* search bar에 date picker 추가
* search결과 없을 때는 어떻게 표현할 것인지?
* pagination >> 실행 후 < 이전 페이지로 돌아갈 때 마이너스 페이지 파거나 1단위가 아닌 페이지로 들어가는 이슈 검토
* 수정페이지에서 주소 변경할 때, 데이터는 반영되나 리렌더 안되는 생명주기의 신비로운 현상 검토
* 대충 밀어붙힌 modal, inline-styles 전량 검토
<br />
<details>
<summary> 파일구조 </summary>
&emsp;
App
ㄴ boards
&emsp;ㄴ[boardId]
&emsp;&emsp;ㄴ edit.
&emsp;&emsp;&emsp;ㄴ `(page). *수정페이지`
&emsp;&emsp;ㄴ `(page). *상세페이지`
&emsp;ㄴnew
&emsp;&emsp;ㄴ `(page). *등록페이지`
&emsp;ㄴ `(page). *페이지리스트`
&emsp;
ㄴ login
&emsp;ㄴ `(page). *로그인페이지`
ㄴcommons
&emsp;ㄴ`graphql setting`
&emsp;&emsp;ㄴ(graphql with codegen)
&emsp;ㄴ`hocs`
&emsp;&emsp;ㄴ(로그인검토 등 위한 상위 …

[241029] 이하성 Day42 과제 제출

---

side-project/next.config.js
side-project/next.config.mjs
side-project/next.config.ts
side-project/package.json
side-project/src/app/globals.css
side-project/src/app/login/page.tsx
side-project/src/app/signup/page.tsx
side-project/src/commons/gql/gql.ts
side-project/src/commons/gql/graphql.ts
side-project/src/commons/hooks/useForm.ts
side-project/src/commons/hooks/useMutationHandler.ts
side-project/src/components/signup/hooks.ts
side-project/src/components/signup/index.tsx
side-project/src/components/signup/queries.ts
side-project/tailwind.config.ts
side-project/yarn.lock

로그인 기능은 아직 진행중이고, 회원가입은 완료했습니다.

[241029] Day42 김민정 필수과제 제출 (진행중)

---

server/.dockerignore
server/.gitignore
server/Dockerfile
server/configs/mongoDB.config.ts
server/configs/postgreSQL.config.ts
server/docker-compose.yml
server/logstash.conf
server/nest-cli.json
server/package-lock.json
server/package.json
server/src/app.module.ts
server/tsconfig.build.json
server/tsconfig.json

우선순위 
1. backend 배포 
1-1. docker setting (clear)
1-2. aws에 container 올리기 
1-3 github action 자동 cicd 구축 
2. 로그인 로직 
2-1. nextauth 로그인 jwt 토큰 발급 
2-1-1. redis로 session 처리해서 client - server 간 jwt 토큰 유효성 검증체크 
2-2. passport를 이용하여 인증처리 
2-3. guard를 이용하여 인가처리 
2-4. client에서 로그인 유효성 체크(globalstate -> access token / cookie -> refresh token)
3. 검색 역인덱스
3-1. ELK (elasticserach / logstash / kibana)랑 mongodb 연결 + 유효시간체크
3-2. redis에다가 캐시메모리 검색 처리하기 
3-3. 실제 client에서 검색 처리하고 백엔드 로그 확인해보기
10/31 목표 9시30분까지 - 배포 및 자동 cicd 구축

[241030] 류지승

---

frontend/next-homework/package.json
frontend/next-homework/src/app/layout.tsx
frontend/next-homework/src/app/page.tsx
frontend/next-homework/src/app/user/login/page.tsx
frontend/next-homework/src/app/user/login/schema.ts
frontend/next-homework/src/app/user/signup/page.tsx
frontend/next-homework/src/app/user/signup/schema.ts
frontend/next-homework/src/commons/layout/index.tsx
frontend/next-homework/src/commons/layout/navigation/hook.ts
frontend/next-homework/src/commons/layout/navigation/index.tsx
frontend/next-homework/yarn.lock

React-hook-form + zod로 구현했습니다.

[241030] 김수연: Day41 과제 제출

---

maincamp/my-app/package.json
maincamp/my-app/src/commons/graphql/gql.ts
maincamp/my-app/src/commons/graphql/graphql.ts
maincamp/my-app/src/components/boards-detail/comment-list/hook.ts
maincamp/my-app/src/components/boards-detail/comment-list/index.tsx
maincamp/my-app/src/components/boards-list/pagination/index.tsx
maincamp/my-app/src/components/boards-write/hook.ts
maincamp/my-app/yarn.lock

[241031] 메인캠프 과제제출 서준형

---

03-trip/03-03-Next/src/commons/hooks/useSubmit.ts
03-trip/03-03-Next/src/commons/hooks/useUpdate.ts
03-trip/03-03-Next/src/commons/types/types.ts
03-trip/03-03-Next/src/components/Molecules/Search/index.tsx
03-trip/03-03-Next/src/components/Molecules/pagination/index.tsx
03-trip/03-03-Next/src/components/Organisms/BoardsDetail/index.tsx
03-trip/03-03-Next/src/components/Organisms/BoardsList/index.tsx

day 44.
1. 제너릭 타입을 추가해주세요. => `HOC에 generic type 적용`
2. 여행상품을 공통컴포넌트로 분리해주세요. => `!!TODO`
* BE(openapi, firebase, fetchpolicy) 시도라도 해보기 `완전 미흡.. 시도조차 안해봄`
* 로그인 드롭다운 구성 `로그인 페이지,기능, 유지, 권한분기 완성`
* 상품페이지 완성하기 `퍼블리싱 완료`
* 마이페이지 완성하기 `미진행`
[완료] search bar에 date picker 추가 => `antd활용하여 완료`
[완료] search결과 없을 때는 어떻게 표현할 것인지? => `조건 추가하여 대응 완료`
[완료] pagination >> 실행 후 < 이전 페이지로 돌아갈 때 마이너스 페이지 파거나 1단위가 아닌 페이지로 들어가는 이슈 검토
=> `멍청이슈 확인 조건 추가하여 디버깅 완료`
[완료] 수정페이지에서 주소 변경할 때, 데이터는 반영되나 리렌더 안되는 생명주기의 신비로운 현상 검토
=> `멍청이슈 확인 조건 추가하여 디버깅 완료`
[TODO] 대충 밀어붙힌 inline-styles 전량 검토 => `미대응`
주말 중 백엔드 복습 및 상품/마이페이지 작업 완료, 시간 남으면 대충 밀어붙힌 스타일 전량 검토 목표
<br />
<details>
<summary> 파일구조 </summary>
&emsp;
App
ㄴ boards
&emsp;ㄴ[boardId]
&emsp;&emsp;ㄴ edit.
&emsp;&emsp;&emsp;ㄴ `(page). *수정페이지`
&emsp;&emsp;ㄴ `(page). *상세페이지` …

[241031] 이하성 Day44 과제 제출

---

side-project/src/commons/ui/Input/index.tsx
side-project/src/commons/ui/button/index.tsx
side-project/src/components/login/hooks.ts
side-project/src/components/login/index.tsx
side-project/src/components/signup/hooks.ts
side-project/src/components/signup/index.tsx
side-project/src/schemas/loginSchema.ts

로그인 페이지에서 공통 컴포넌트 및 zod 유틸리티 타입을 적용했고, 회원가입 페이지에선 적용중입니다.

[241031] Day44 김민정 필수과제 제출

---

my-app/src/app/layout.tsx
my-app/src/app/purchase/page.tsx
my-app/src/app/purchase/purchaseWrite/page.tsx
my-app/src/commons/layout/navigation/index.tsx
my-app/src/commons/settings/apollo-header-setting-localstorage.tsx
my-app/src/components/authentication/login/index.tsx
my-app/src/components/purchase/purchase-main/index.tsx
my-app/src/components/purchase/purchase-write/index.tsx
my-app/src/components/purchase/purchase-write/styles.module.css

D-39 상품페이지 퍼블리싱 진행중이며, D-42 로그인  완료 했습니다.

[241104] day-39,42 이찬우 과제 제출

---

class-practice/my-app/package.json
class-practice/my-app/src/app/layout.tsx
class-practice/my-app/src/app/section26/26-01-login-refreshtoken/page.tsx
class-practice/my-app/src/app/section26/26-01-login-resfreshtoken-success/page.tsx
class-practice/my-app/src/app/section26/26-02-login-refreshtoken-refresh/page.tsx
class-practice/my-app/src/app/section26/26-02-login-resfreshtoken-refresh-success/page.tsx
class-practice/my-app/src/app/section26/26-02-observable-flatmap/page.tsx
class-practice/my-app/src/commons/hocs/26-02-with로그인체크.tsx
class-practice/my-app/src/commons/libraries/26-01-get-access-token.ts
class-practice/my-app/src/commons/settings/26-01-apollo-header-and-error-setting.tsx
class-practice/my-app/src/commons/settings/26-02-apollo-header-and-error-setting-refresh.tsx
class-practice/my-app/src/commons/stores/26-02-load-store.ts
class-practice/my-app/yarn.lock
homework/my-app/src/app/store/[boardId]/page.tsx
homework/my-app/src/app/store/[boardId]/style.module.css
homework/my-app/src/components/store-comment-answer/index.tsx
homework/my-app/src/components/store-comment-write/index.tsx

[241105]DAY43필수과제제출_임윤정

---

side-project/.eslintrc.json
side-project/package.json
side-project/src/app/mypage/page.tsx
side-project/src/commons/hocs/withLoginCheck.tsx
side-project/src/commons/libraries/accessTokenRefresh.ts
side-project/src/commons/setting/apollo-setting.tsx
side-project/src/commons/stores/accessToken.ts
side-project/src/commons/stores/loadStore.ts
side-project/src/commons/ui/Input/index.tsx
side-project/src/commons/ui/button/index.tsx
side-project/src/components/login/hooks.ts
side-project/src/components/login/index.tsx
side-project/src/components/mypage/index.tsx
side-project/src/components/signup/index.tsx
side-project/src/graphql/mutations/createUser/createUser.generated.ts
side-project/src/graphql/types.ts
side-project/yarn.lock

refreshToken 적용완료했고, 현재 최대한 시맨틱태그를 활용하여 마이페이지 생성하는 중입니다.

[241106] 김민정 Day46 과제제출

---

side-project/codegen.ts
side-project/package.json
side-project/src/app/boards/new/page.tsx
side-project/src/components/boardsManager/hooks.ts
side-project/src/components/boardsManager/index.tsx
side-project/src/graphql/mutations/createBoard/createBoard.generated.ts
side-project/src/graphql/mutations/createBoard/createBoard.graphql
side-project/src/graphql/mutations/updateBoard/updateBoard.generated.ts
side-project/src/graphql/mutations/updateBoard/updateBoard.graphql
side-project/src/graphql/queries/fetchBoard/fetchBoard.generated.ts
side-project/src/graphql/queries/fetchBoard/fetchBoard.graphql
side-project/src/schemas/boardsManagerSchema.ts
side-project/yarn.lock

웹 에디터를 적용했으나, 백엔드와의 연동은 진행 중입니다.

[241107] 김민정 Day49 필수과제 제출

---

side-project/src/app/boards/[boardId]/page.tsx
side-project/src/app/layout.tsx
side-project/src/app/main/page.tsx
side-project/src/app/page.tsx
side-project/src/commons/hocs/withLoginCheck.tsx
side-project/src/commons/libraries/accessTokenRefresh.ts
side-project/src/commons/setting/apollo-setting.tsx
side-project/src/commons/ui/button/index.tsx
side-project/src/components/boardsManager/hooks.ts
side-project/src/components/boardsManager/index.tsx
side-project/src/components/login/hooks.ts
side-project/src/context/AuthContext.tsx
side-project/src/graphql/mutations/uploadFile/uploadFile.generated.ts
side-project/src/graphql/mutations/uploadFile/uploadFile.graphql
side-project/src/graphql/queries/fetchBoard/fetchBoard.generated.ts
side-project/src/schemas/boardsManagerSchema.ts
side-project/yarn.lock

[241111] Day51 김민정 필수과제 제출

---

my-app/src/components/purchase/purchase-detail/detail/index.tsx
my-app/src/components/purchase/purchase-detail/detail/styles.module.css
my-app/src/components/purchase/purchase-write/index.tsx
my-app/src/components/purchase/purchase-write/queries.ts

39 퍼블리싱 완료, 이미지 많이 불러오기까지 완성했는데 gql 수정해야함,   => 완성
43 react-hook-form, zod 사용함, gql 추가적으로 더 넣어줘야 함.  => 완성
47 포트원 연결 했고 gql 수정해야함  => 완성

[241112] day-39, 43, 47,  이찬우 과제 제출

---

trip-talk/package-lock.json
trip-talk/package.json
trip-talk/src/app/_components/ControllerInput/ControllerInput.tsx
trip-talk/src/app/_components/CustomDatePicker/styles.module.css
trip-talk/src/app/_components/Login/Login.tsx
trip-talk/src/app/_components/SignUp/SignUp.tsx
trip-talk/src/app/boards/page.tsx
trip-talk/src/app/layout.tsx
trip-talk/src/app/page.tsx
trip-talk/src/commons/Libraries/getAccessToken.ts
trip-talk/src/commons/hooks/useLayoutHeader.ts
trip-talk/src/commons/hooks/useSignUp.ts
trip-talk/src/commons/layout/banner/index.tsx
trip-talk/src/commons/layout/header/index.tsx
trip-talk/src/commons/layout/layout/index.tsx
trip-talk/src/commons/settings/apollo-setting.tsx
trip-talk/src/constants/constants.ts

refreshToken 적용... 어렵네요.. 흐흡...

[241113] 강예슬 과제 제출

---

my-app/src/commons/hocs/withAuth.tsx
my-app/src/commons/layout/navigation/index.tsx
my-app/src/components/purchase/purchase-detail/detail/index.tsx
my-app/src/components/purchase/purchase-write/index.tsx

hocs 파일 따로 만들어서 분기처리 하는 부분을 빼먹고 한거 같아서 거기 부분 따로 분리해서 수정했습니다.

[241113]  이찬우 과제 제출

---

homework-intermediate/day52/src/components/boards-detail/comment-list/comment-list-item/index.tsx
homework-intermediate/day52/src/components/boards-detail/comment-write/index.tsx
homework-intermediate/day52/src/components/boards-detail/comment-write/queries.ts
homework-intermediate/day52/src/components/products-detail/index.tsx
homework-intermediate/day52/src/components/products-write/index.tsx

1. 트립토크 상세 페이지
~1. 좋아요 기능을 optimistic ui로 업데이트 해주세요.~
2. 여행상품 상세 페이지
~1. 댓글 등록: refetchQueries를 cache.modify로 변경하여 리페치 성능을 개선해주세요.~
~2. 댓글 삭제: refetchQueries를 cache.modify로 변경하여 리페치 성능을 개선해주세요.~
~3. 스크랩: refetchQueries를 cache.modify로 변경하여 리페치 성능을 개선해주세요.~
3. 마이 페이지
1. 거래내역&북마크
1. 나의 상품
1. 글 삭제: refetchQueries를 cache.modify로 변경하여 리페치 성능을 개선해주세요.
4. 트립토크 메인 페이지
1. 게시판
1. 글 삭제: refetchQueries를 cache.modify로 변경하여 리페치 성능을 개선해주세요.

[241120] 박진태 필수 과제 제출
